# ********RoostGPT********

# Test generated by RoostGPT for test apispec-test_clone using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /cancelProductOrder/{order.Id}_post for http method type POST 
# RoostTestHash=cddbe4a76c
# 
# 

# ********RoostGPT********
Feature: Cancel Product Order By Id

  Background:
    * def baseURL = karate.properties['PRODUCTORDERING_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure report = true
    * configure headers = { Accept: 'application/json' }

  Scenario Outline: Cancel Product Order By Id - Valid Request
    Given path '/cancelProductOrder/<orderId>'
    And request
      """
      {
          "order": {
              "associatedDocument": "<associatedDocument>",
              "customer": {
                  "subscriberId": "<subscriberId>"
              }
          }
      }
      """
    When method POST
    Then status 200
    And match response ==
      """
      {
          "control": {
              "code": "200",
              "message": "#string",
              "type": "S"
          }
      }
      """

    Examples:
      | read('cancelProductOrder_order.Id_post.csv') |

  Scenario Outline: Cancel Product Order By Id - Invalid Request
    Given path '/cancelProductOrder/<orderId>'
    And request
      """
      {
          "order": {
              "associatedDocument": "<associatedDocument>",
              "customer": {
                  "subscriberId": "<subscriberId>"
              }
          }
      }
      """
    When method POST
    Then status 400
    And match response ==
      """
      {
          "control": {
              "code": "400",
              "message": "#string",
              "type": "E"
          }
      }
      """

    Examples:
      | orderId          | associatedDocument | subscriberId |
      | '20230315000001' | 'VTT001'           | 'SVTAL001'   |

  Scenario Outline: Cancel Product Order By Id - Unauthorized
    Given path '/cancelProductOrder/<orderId>'
    And request
      """
      {
          "order": {
              "associatedDocument": "<associatedDocument>",
              "customer": {
                  "subscriberId": "<subscriberId>"
              }
          }
      }
      """
    When method POST
    Then status 401
    And match response ==
      """
      {
          "control": {
              "code": "401",
              "message": "#string",
              "type": "E"
          }
      }
      """

    Examples:
      | orderId          | associatedDocument | subscriberId |
      | '20230315000001' | 'VTT001'           | 'SVTAL001'   |

  Scenario Outline: Cancel Product Order By Id - Forbidden
    Given path '/cancelProductOrder/<orderId>'
    And request
      """
      {
          "order": {
              "associatedDocument": "<associatedDocument>",
              "customer": {
                  "subscriberId": "<subscriberId>"
              }
          }
      }
      """
    When method POST
    Then status 403
    And match response ==
      """
      {
          "control": {
              "code": "403",
              "message": "#string",
              "type": "E"
          }
      }
      """

    Examples:
      | orderId          | associatedDocument | subscriberId |
      | '20230315000001' | 'VTT001'           | 'SVTAL001'   |

  Scenario Outline: Cancel Product Order By Id - Not Found
    Given path '/cancelProductOrder/<orderId>'
    And request
      """
      {
          "order": {
              "associatedDocument": "<associatedDocument>",
              "customer": {
                  "subscriberId": "<subscriberId>"
              }
          }
      }
      """
    When method POST
    Then status 404
    And match response ==
      """
      {
          "control": {
              "code": "404",
              "message": "#string",
              "type": "E"
          }
      }
      """

    Examples:
      | orderId          | associatedDocument | subscriberId |
      | '20230315000001' | 'VTT001'           | 'SVTAL001'   |

  Scenario Outline: Cancel Product Order By Id - Not Acceptable
    Given path '/cancelProductOrder/<orderId>'
    And request
      """
      {
          "order": {
              "associatedDocument": "<associatedDocument>",
              "customer": {
                  "subscriberId": "<subscriberId>"
              }
          }
      }
      """
    When method POST
    Then status 406
    And match response ==
      """
      {
          "control": {
              "code": "406",
              "message": "#string",
              "type": "E"
          }
      }
      """

    Examples:
      | orderId          | associatedDocument | subscriberId |
      | '20230315000001' | 'VTT001'           | 'SVTAL001'   |

  Scenario Outline: Cancel Product Order By Id - Locked
    Given path '/cancelProductOrder/<orderId>'
    And request
      """
      {
          "order": {
              "associatedDocument": "<associatedDocument>",
              "customer": {
                  "subscriberId": "<subscriberId>"
              }
          }
      }
      """
    When method POST
    Then status 423
    And match response ==
      """
      {
          "control": {
              "code": "423",
              "message": "#string",
              "type": "E"
          }
      }
      """

    Examples:
      | orderId          | associatedDocument | subscriberId |
      | '20230315000001' | 'VTT001'           | 'SVTAL001'   |

  Scenario Outline: Cancel Product Order By Id - Too Many Requests
    Given path '/cancelProductOrder/<orderId>'
    And request
      """
      {
          "order": {
              "associatedDocument": "<associatedDocument>",
              "customer": {
                  "subscriberId": "<subscriberId>"
              }
          }
      }
      """
    When method POST
    Then status 429
    And match response ==
      """
      {
          "control": {
              "code": "429",
              "message": "#string",
              "type": "E"
          }
      }
      """

    Examples:
      | orderId          | associatedDocument | subscriberId |
      | '20230315000001' | 'VTT001'           | 'SVTAL001'   |

  Scenario Outline: Cancel Product Order By Id - Internal Server Error
    Given path '/cancelProductOrder/<orderId>'
    And request
      """
      {
          "order": {
              "associatedDocument": "<associatedDocument>",
              "customer": {
                  "subscriberId": "<subscriberId>"
              }
          }
      }
      """
    When method POST
    Then status 500
    And match response ==
      """
      {
          "control": {
              "code": "500",
              "message": "#string",
              "type": "T"
          }
      }
      """

    Examples:
      | orderId          | associatedDocument | subscriberId |
      | '20230315000001' | 'VTT001'           | 'SVTAL001'   |

  Scenario Outline: Cancel Product Order By Id - Service Unavailable
    Given path '/cancelProductOrder/<orderId>'
    And request
      """
      {
          "order": {
              "associatedDocument": "<associatedDocument>",
              "customer": {
                  "subscriberId": "<subscriberId>"
              }
          }
      }
      """
    When method POST
    Then status 503
    And match response ==
      """
      {
          "control": {
              "code": "503",
              "message": "#string",
              "type": "T"
          }
      }
      """

    Examples:
      | orderId          | associatedDocument | subscriberId |
      | '20230315000001' | 'VTT001'           | 'SVTAL001'   |

  Scenario Outline: Cancel Product Order By Id - Gateway Timeout
    Given path '/cancelProductOrder/<orderId>'
    And request
      """
      {
          "order": {
              "associatedDocument": "<associatedDocument>",
              "customer": {
                  "subscriberId": "<subscriberId>"
              }
          }
      }
      """
    When method POST
    Then status 504
    And match response ==
      """
      {
          "control": {
              "code": "504",
              "message": "#string",
              "type": "T"
          }
      }
      """

    Examples:
      | orderId          | associatedDocument | subscriberId |
      | '20230315000001' | 'VTT001'           | 'SVTAL001'   |
